### ISSUE TITLE
Change deadline number of days

### ISSUE THREAD

**Issue by ghost** [MikeS-MS/MikesTweaks#1]
Hey, loving your work so far!

I was wondering if it would be possible to change the number of days of the deadline? Like through a value in the settings config file or maybe by incrementing _n_ days every time the profit quota is reached.

Thank you!

**Comment by MikeS-MS** [comment]
I'll have a look at it, but for the "time" side of things in general there's someone already working on one that will allow full time control and what you ask will be included in it.

**Comment by MikeS-MS** [comment]
@guterino The mod that I was talking about in my previous message still hasn't been released I think, but I found [this](https://thunderstore.io/c/lethal-company/p/AMRV/LethalCompanyVariables/) one if you'd like to give it a look. It allows you to set the amount of days to complete the quota in. 

There's also [this](https://thunderstore.io/c/lethal-company/p/oknorton/LethalCompanyBetterScaling/) one, though according to #10 my mod's networking gets completely broken when paired with it.

I do not plan to add that as an option in mine due to other mods having it already and it would be pointless to have many overlapping features.
