### ISSUE TITLE
Additional Item Slots do not appear when using LethalCompanyBetterScaling

### ISSUE THREAD

**Issue by GarethCarew** [MikeS-MS/MikesTweaks#10]
As in the title, the additional item slots do not work for non-hosts when using [LethalCompanyBetterScaling](https://github.com/oknorton/LethalCompanyScalingMaster). Item slots still appear for host. 

Tried on versions 1.8.0 and 1.8.1.

**Comment by MikeS-MS** [comment]
This seems to be an issue caused by LethalCompanyBetterScaling, not something I can fix on my side I think, because even with just the LethalCompanyBetterScaling mod enabled it throws a couple of errors only on the client side. I'm assuming that the mod causing exceptions to be thrown breaks any other mod or at least maybe the networking? I'm saying only the networking part because the hotkeys seem to work, but nothing network related works, no config syncs, no slot change replication from client to host, nothing. I've let the dev know about it oknorton/LethalCompanyScalingMaster#1

**Comment by Terrified057T** [comment]
Made an account to add onto this, I don't have the better scaling mod but the host still has 2 extra slots and every other player has the default 4 even with a modification of their config file. Switch it around, X player will have the host benefit and Z who was the previous host is down to default 4. Can't see any mods that may conflict, as I am not a comp sci guy. I'll list the mods tho: better spraypaint, forest giant motion sense, light switch no more, more company, more screams, skinwalker mod and mike's tweaks.

**Comment by MikeS-MS** [comment]
> Made an account to add onto this, I don't have the better scaling mod but the host still has 2 extra slots and every other player has the default 4 even with a modification of their config file. Switch it around, X player will have the host benefit and Z who was the previous host is down to default 4. Can't see any mods that may conflict, as I am not a comp sci guy. I'll list the mods tho: better spraypaint, forest giant motion sense, light switch no more, more company, more screams, skinwalker mod and mike's tweaks.

Please make a separate issue if it's not related to the source of this issue and provide as much information as possible.
