### ISSUE TITLE
[BUG] StaminaRechargePerFrame doesn't work

### ISSUE THREAD

**Issue by Entity378** [MikeS-MS/MikesTweaks#28]
**Mods:**
```
 - MikesTweaks V2.0.2 (status: enabled)
```
**Configs:**
```
- MikesTweaks :
StaminaRechargePerFrame = 5 or any other value
```

**Where does the issue happen (client-side/host-side/both)?:**
Both sides experience this issue

**Explain the issue:** 
Regardless of the set value of StaminaRechargePerFrame, stamina always regenerates at the same speed.
I wish I could give more information than this, but even after looking in the logs, I couldn't find anything useful.

**Comment by MikeS-MS** [comment]
I'm going to need you to give me all the information from the [bug report template](https://github.com/MikeS-MS/MikesTweaks/blob/main/.github/ISSUE_TEMPLATE/bug-report.md).

**Comment by Entity378** [comment]
> I'm going to need you to give me all the information from the [bug report template](https://github.com/MikeS-MS/MikesTweaks/blob/main/.github/ISSUE_TEMPLATE/bug-report.md).

I updated the issue, is it ok now?
​

**Comment by MikeS-MS** [comment]
I'm assuming since you only put my mod in the `Mods` section you only have mine and no other mod enabled right? If that's the case, I tried reproducing it and it didn't happen for me, neither on v45, nor v47, nor v49. It works properly and there were also no errors in the console. Are you sure you haven't put `UseVanillaStaminaValues` to true? That would force every stamina related value to be vanilla and not be changed to whatever you set them as. If that's not it, could you try on a clean save slot?

**Comment by Entity378** [comment]
I tried to fix the problem by doing random things and eventually I solved the problem, I don't even know what caused the problem. Anyway, thanks for your patience
