### ISSUE TITLE
More item slots don't work for anyone but host

### ISSUE THREAD

**Issue by Nipeno** [MikeS-MS/MikesTweaks#7]
Seems to be broken rn

**Comment by MikeS-MS** [comment]
What version are you on and what other mods do you have (if any)?

**Comment by xamionex** [comment]
> What version are you on and what other mods do you have (if any)?

Game: v40
Mod: v1.8

Mods
```
BepInExPack by BepInEx
VoiceHUD by 5Bit
GameMaster by GameMasterDevs
Lethal_Company_Enhancer by Mom_Llama
LC_Symphony by alexanderjoe
ObjectVolumeController by FlipMods
LetMeLookDown by FlipMods
LC_Better_Teleport by JT
Solos_Ring_Compass by CapyCat
ShipLoot by tinyhoot
More_Suits by x753
FriendlyFirelessCompany by RogerFK_TEAM
LC_API by 2018
NoPenalty by bizzlemip
QuickRestart by AllToasters
UnlimitedTZP by ATK
AdditionalSuits by AlexCodesGames
Pinger by MoreLethal
MoreItems by Drakorle
ShipClock by ATK
Glow_Steps by Ozone
HealthStation by Thorlar
HDLethalCompany by Sligili (version 1.3.0)
MikesTweaks by MikeMediaStudios
FasterItemDropship by FlipMods (version 1.0.2)
Solos_Bodycams by CapyCat
ShipLobby by tinyhoot
NoBackgroundAudio by MoreLethal
```

If the other person could post their mods too we'd be able to find common mods and see if it's a compatibility issue

Also if it's any help version 1.6.5 works perfectly

**Comment by xamionex** [comment]
I'll keep testing around but it seems to be fixed in 1.8, very weird issue, not sure what mods I had to make it not work, will update if it happens again but you can rule out the mods I have if anything

**Comment by MikeS-MS** [comment]
> I'll keep testing around but it seems to be fixed in 1.8, very weird issue, not sure what mods I had to make it not work, will update if it happens again but you can rule out the mods I have if anything

What was the version the issue was happening in? Pre 1.6.5 or 1.7? Because I know in 1.6.3 there was some related issue and I fixed it in 1.6.4.

**Comment by xamionex** [comment]
> What was the version the issue was happening in? Pre 1.6.5 or 1.7? Because I know in 1.6.3 there was some related issue and I fixed it in 1.6.4.

It happened in 1.7, that's when I downgraded because slots didn't work, I don't know but you could try testing with LateCompany, that was a mod I had before but then I removed it because it caused issues, I also had Custom Boombox Music but I doubt that's the mod causing incompatibilities

**Comment by MikeS-MS** [comment]
Did it happen when people joined late, or when they joined normally before you even started the game, or both?

**Comment by xamionex** [comment]
> Did it happen when people joined late, or when they joined normally before you even started the game, or both?

Normal join, the LateCompany mod was causing issues like desyncs with items and so we removed it

**Comment by MikeS-MS** [comment]
It seems LateCompany works. I tested it and clients do in fact have everything working. But Late joining seems to cause some other errors, don't know if those persist with the mod on its own or paired with mine.

**Comment by xamionex** [comment]
> It seems LateCompany works. I tested it and clients do in fact have everything working. But Late joining seems to cause some other errors, don't know if those persist with the mod on its own or paired with mine.

Not sure how I can help unless the OP posts their modlist and we see some common mods, I can't revert deleted mods so I guess until I find the mod in question I can't help any more

**Comment by Nipeno** [comment]
Sorry for the late reply
This is my modlist
- BepInExPack
- MikesTweaks
- WalkieUse
- FlashlightToggle
- LateCompany
- HDLethalCompany
- LetMeLookDown
- FasterItemDropship
- LC_Better_Teleport
- ShipLoot
- LCBetterSaves
- FOV_Adjust
- LC_API
- MoreCompany

**Comment by MikeS-MS** [comment]
> Sorry for the late reply This is my modlist
> 
> * BepInExPack
> * MikesTweaks
> * WalkieUse
> * FlashlightToggle
> * LateCompany
> * HDLethalCompany
> * LetMeLookDown
> * FasterItemDropship
> * LC_Better_Teleport
> * ShipLoot
> * LCBetterSaves
> * FOV_Adjust
> * LC_API
> * MoreCompany

Ok what version of MikesTweaks were you using?

**Comment by xamionex** [comment]
### Common Mods as of right now:

BepInExPack by BepInEx
LetMeLookDown by FlipMods
LC_Better_Teleport by JT
ShipLoot by tinyhoot
LC_API by 2018
HDLethalCompany by Sligili (v1.3.0, the issues newer version had have been fixed, you can install latest)
FasterItemDropship by FlipMods (v1.0.2, 1.1.2 said they fixed the ship landing bug, but it still happens to me)
MikesTweaks by MikeMediaStudios

### Common Mods that I deleted:
[FOV_Adjust by Rozebud](https://thunderstore.io/c/lethal-company/p/Rozebud/FOV_Adjust/)
[LateCompany by anormaltwig](https://thunderstore.io/c/lethal-company/p/anormaltwig/LateCompany/)
[WalkieUse by Renegades](https://thunderstore.io/c/lethal-company/p/Renegades/WalkieUse/) (Removed because MikesTweaks has it)
[FlashlightToggle by Renegades](https://thunderstore.io/c/lethal-company/p/Renegades/FlashlightToggle/) (Removed because MikesTweaks has it)

**Comment by xamionex** [comment]
I don't know if it will help you but HDLethalCompany and FOV_Adjust used to conflict somewhat I think (fog would disappear if you weren't looking at lights) but I don't know if that's the case still, either way your priority should be testing with these mods I guess.

Also in my case GameMaster would conflict with HDLethalCompany (versions 1.4.0-1.4.1)

Hope I helped and good luck fixing this, wish more people paid attention to your mod cause it's good.

**Comment by MikeS-MS** [comment]
> ### Common Mods as of right now:
> BepInExPack by BepInEx
> LetMeLookDown by FlipMods
> LC_Better_Teleport by JT
> ShipLoot by tinyhoot
> LC_API by 2018
> HDLethalCompany by Sligili (v1.3.0, the issues newer version had have been fixed, you can install latest)
> FasterItemDropship by FlipMods (v1.0.2, 1.1.2 said they fixed the ship landing bug, but it still happens to me)
> MikesTweaks by MikeMediaStudios
> 
> ### Common Mods that I deleted:
> [FOV_Adjust by Rozebud](https://thunderstore.io/c/lethal-company/p/Rozebud/FOV_Adjust/) 
> [LateCompany by anormaltwig](https://thunderstore.io/c/lethal-company/p/anormaltwig/LateCompany/) 
> [WalkieUse by Renegades](https://thunderstore.io/c/lethal-company/p/Renegades/WalkieUse/) (Removed because MikesTweaks has it) 
> [FlashlightToggle by Renegades](https://thunderstore.io/c/lethal-company/p/Renegades/FlashlightToggle/) (Removed because MikesTweaks has it)

As far as I know from playing with friends, HDLethalCompany, ShipLoot and LC_API do not cause issues paired with MikesTweaks. We've played for a while using the following without problems: 

- BrutalCompany
- ShipLoot
- ShipClock
- HDLethalCompany
- LC_API 
- BepinEx

You said that now in 1.8 it's fine for you @xamionex, right? 

I also tested with LateCompany and MikesTweaks (just those 2) yesterday and it also seems to not cause issues. Tho LateCompany had an update yesterday apparently so that might be why.

Just tested with the following (all latest versions and default configs), no issues running them together at first glance (no missing inventory slots or not working hotkeys), haven't tested deeper than checking if my configs sync correctly, which they do:
-   LC_API
-   LateCompany
-   FasterItemDropship
-   LetMeLookDown
-   LC_Better_Teleport
-   MikesTweaks
-   FlashlightToggle
-   WalkieUse
-   ShipLoot

Tested with this entire modlist too (again latest versions with default configs), seems to work without issues, the only reason why I separated this test is because MoreCompany, LCBetterSaves and HDLethalCompany throw errors on their own, so it's entirely possible on a different machine that when those errors occur, a lot of things after them cannot be executed (my mod's inventory setup for example):
- BepInExPack
- MikesTweaks
- WalkieUse
- FlashlightToggle
- LateCompany
- HDLethalCompany
- LetMeLookDown
- FasterItemDropship
- LC_Better_Teleport
- ShipLoot
- LCBetterSaves
- FOV_Adjust
- LC_API
- MoreCompany

If you could, can you test those 3 modlists to see if any of them cause you issues with other people? Keep in mind you will all need to have the same ones for the tests.

**Comment by Nipeno** [comment]
I was using 1.7, seems like it is fixed now.

**Comment by xamionex** [comment]
Seems it was just an issue with 1.7, updated after seeing this and it works.

![26d;01h;08m;09s;609ms](https://github.com/MikeS-MS/MikesTweaks/assets/57235791/dd1854c7-1e81-4619-b674-d4ef11f61859)

**Comment by MikeS-MS** [comment]
The thing is I haven't even touched that part of the mod between those 2 versions, only thing I did was add more (the moon costs and the corresponding game rule), most likely another mod was causing the issue, but it updated? I'm glad it's not happening anymore, as MikesTweaks on its own should not be having that issue since v1.6.4. Feel free to open another issue if it keeps happening at some point.
